/**:
  ros__parameters:
    user_defined_initial_pose.enable: true
    user_defined_initial_pose.pose: [30, 30, 0, 0, 0, 0, 1]
    gnss_pose_timeout: 3.0 # [sec]
    stop_check_duration: 3.0 # [sec]
    stop_check_enabled: false
    gnss_enabled: false
    ekf_enabled: false
    yabloc_enabled: false
    ndt_enabled: true

    # from gnss
    gnss_particle_covariance:
      [
        1.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 1.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.01, 0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.01, 0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.01, 0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  10.0,
      ]

    # output
    output_pose_covariance:
      [
        1.0, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 1.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.01, 0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.01, 0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.01, 0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.2,
      ]
